services:
 ocm_admin:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SERVICE_PORT=${SERVICE_PORT}
        - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
        - NEXT_PUBLIC_WEB_PATH=${NEXT_PUBLIC_WEB_PATH}
        - NEXT_PUBLIC_POS_PATH=${NEXT_PUBLIC_POS_PATH}
        - NEXT_PUBLIC_TINYMCE_API_KEY=${NEXT_PUBLIC_TINYMCE_API_KEY}
    container_name: saas_admin
    expose:
      - "${SERVICE_PORT}"
    ports:
      - ${SERVICE_PORT}:${SERVICE_PORT}
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: always
